### ISSUE TITLE
Horizontal `TabBar` item changes after being pressed

### ISSUE THREAD

**Issue by aytunch** [wayne900204/vertical_scrollable_tabview#13]
Let's say my tab bar item index is 0
If I press Tabbar item with index=3, both the Vertical view and the Horizontal tabbar scrolls to the right place.
However, instantly the horizontal tabbar scroll backs to index=2.

As you can see from the video, this only happens ~~if we are going from a smaller index to a higher index AND~~ if that particular index has lots of items in them (more than the screen height).

@wayne900204 Can you please look into this bug? Thank you.

https://user-images.githubusercontent.com/6442915/158272351-ad7f930b-f747-4428-bf98-68fb8fb79696.mov

**Comment by wayne900204** [comment]
I will try to look into this bug

**Comment by erkansahin** [comment]
I have the same issue

**Comment by mohamedalaaser** [comment]
I had the same issue and tried to understand what was happening. I found out that the method `getVisibleItemsIndex()` sometimes returns indices that are not even visible on the screen. I found out that this happens because for some reason the list I was having was overlapping with the AppBar (the list items were going below it), so to the `getVisibleItemsIndex()` method, they are visible until they are scrolled out from below the AppBar as well. To fix this I altered the method to make sure it does not return the item if it is only under the AppBar by adding the height of the AppBar to the if condition.

`List<int> getVisibleItemsIndex() {
    // get ListView Rect
    Rect? rect = RectGetter.getRectFromKey(listViewKey);
    List<int> items = [];
    if (rect == null) return items;
    /// TODO Horizontal ScrollDirection
    // bool isHoriontalScroll = widget._axisOrientation == Axis.horizontal;
    bool isHoriontalScroll = false;
    itemsKeys.forEach((index, key) {
      Rect? itemRect = RectGetter.getRectFromKey(key);
      if (itemRect == null) return;
      // y 軸座越大，代表越下面
      // 如果 item 上方的座標 比 listView 的下方的座標 的位置的大 代表不在畫面中。
      // bottom meaning => The offset of the bottom edge of this widget from the y axis.
      // top meaning => The offset of the top edge of this widget from the y axis.
      //Change offset based on AxisOrientation [horizontal] [vertical]
      switch (isHoriontalScroll) {
        case true:
          if (itemRect.left > rect.right) return;
          // 如果 item 下方的座標 比 listView 的上方的座標 的位置的小 代表不在畫面中。
          if (itemRect.right < rect.left) return;
          break;
        default:
          if (itemRect.top > rect.bottom) return;
          // 如果 item 下方的座標 比 listView 的上方的座標 的位置的小 代表不在畫面中。
          if (itemRect.bottom < rect.top + MediaQuery.of(context).viewPadding.top +
              kToolbarHeight +
              65) return;
      }

      items.add(index);
    });
    return items;
  }`

**Comment by mohamedalaaser** [comment]
when you click on a tab, the `onScrollNotification()` method is called after the controller scrolls to that tab, the method then does its job and animates the tab controller to the middle visible tab

**Comment by mohamedalaaser** [comment]
The `getVisibleItemsIndex()` method sometimes returns an index of an item that is not visible on the screen. It only stops returning this index if you scroll a little more past the length of the AppBar.
So if you alter this if condition:
 ` if (itemRect.bottom < rect.top ) return;`
To this:
` if (itemRect.bottom < rect.top + MediaQuery.of(context).viewPadding.top +kToolbarHeight +56) return;`

This will make sure the method will not return the index once the item is out of the view (but maybe still under the Appbar).
I didn't have the time to dig more into a better solution to the problem but this works fine for me.

It will solve the problem in most cases but not in the case where there are three categories visible on the screen. because in this case, the `onScrollNotification()` will do its job and animate the tab controller to the middle category.

**Comment by wayne900204** [comment]
Thanks @mohamedalaaser

**Comment by aytunch** [comment]
@mohamedalaaser @wayne900204 thank you for the fixes. I have tested with the new version.
But currently there is another problem as you can see in these 2 videos.
1-When "Bao" is pressed, indicator goes to "Highlighted" momentarily and then goes back to "Bao"
2-When we scroll the horizontal bar all the way to the end and press the last category, the whole horizontal scroll goes back to the beginning(current category) and scrolls again to the last item

https://user-images.githubusercontent.com/6442915/161397432-11160663-38cd-413b-8e16-1b084f2c6a7c.mov


https://user-images.githubusercontent.com/6442915/161397441-445bd5ef-2b2c-4469-af88-b35a22df471d.mov

**Comment by mohamedalaaser** [comment]
@aytunch this doesn't happen with me :/ 
can you please share your code? ill try to see what's going on

**Comment by wayne900204** [comment]
@aytunch Can you please share your code?

**Comment by shahmirzali49** [comment]
@wayne900204 thanks for the package but, this problem is also in your example(folder) code, you can look there.

**Comment by nikiforosper** [comment]
I have the same issue, too

> @mohamedalaaser @wayne900204 thank you for the fixes. I have tested with the new version. But currently there is another problem as you can see in these 2 videos. 1-When "Bao" is pressed, indicator goes to "Highlighted" momentarily and then goes back to "Bao" 2-When we scroll the horizontal bar all the way to the end and press the last category, the whole horizontal scroll goes back to the beginning(current category) and scrolls again to the last item
> 
>  Screen.Recording.2022-04-02.at.21.49.49.mov 
>  Screen.Recording.2022-04-02.at.21.52.56.mov

I have the same issue,too

**Comment by aleksandar-radivojevic** [comment]
@wayne900204 Any updates on this?

**Comment by wayne900204** [comment]
already fixed.
